repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy .
        types: [python]
        pass_filenames: false

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        types: [python]